// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Artifact struct {
	ID            string
	ReleaseID     string
	TrackID       string
	ArtifactKind  string
	IsCanonical   int64
	Filename      string
	MimeType      string
	Sha256        string
	StorageRef    string
	BuiltAt       string
	State         string
	MetadataRef   string
	NormalizedRef string
	RawRef        string
}

type Lease struct {
	Key       string
	Holder    string
	ExpiresAt string
	UpdatedAt string
}

type PublishRecord struct {
	ID          string
	ArtifactID  string
	TargetID    string
	TargetKind  string
	TargetRef   string
	PublishHash string
	PublishedAt string
	Status      string
	Message     string
}

type Release struct {
	ID                   string
	SourceID             string
	ProviderReleaseID    string
	Url                  string
	Title                string
	PublishedAt          string
	EditedAt             string
	PostType             string
	VisibilityState      string
	NormalizedPayloadRef string
	RawPayloadRef        string
	ContentHash          string
	DiscoveredAt         string
	Status               string
}

type ReleaseAssignment struct {
	ReleaseID   string
	TrackID     string
	RuleID      string
	ReleaseRole string
	Confidence  float64
}

type RunRecord struct {
	ID          string
	Command     string
	StartedAt   string
	FinishedAt  sql.NullString
	Status      string
	Summary     string
	SourceScope string
	DryRun      int64
}

type Source struct {
	ID            string
	Provider      string
	SourceUrl     string
	SourceType    string
	CreatorID     string
	CreatorName   string
	AuthProfileID string
	Enabled       int64
	SyncCursor    string
	LastSyncedAt  string
}

type StoryTrack struct {
	ID              string
	SourceID        string
	TrackKey        string
	TrackName       string
	CanonicalAuthor string
	SeriesMeta      string
	OutputPolicy    string
	CreatedAt       string
	UpdatedAt       string
}
