// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const acquireLease = `-- name: AcquireLease :execrows
INSERT INTO leases (key, holder, expires_at, updated_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(key) DO UPDATE SET
  holder = excluded.holder,
  expires_at = excluded.expires_at,
  updated_at = excluded.updated_at
WHERE leases.expires_at <= excluded.updated_at
   OR leases.holder = excluded.holder
`

type AcquireLeaseParams struct {
	Key       string
	Holder    string
	ExpiresAt string
	UpdatedAt string
}

func (q *Queries) AcquireLease(ctx context.Context, arg AcquireLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acquireLease,
		arg.Key,
		arg.Holder,
		arg.ExpiresAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearCanonicalArtifactsForRelease = `-- name: ClearCanonicalArtifactsForRelease :exec
UPDATE artifacts
SET is_canonical = 0
WHERE release_id = ?1
`

func (q *Queries) ClearCanonicalArtifactsForRelease(ctx context.Context, releaseID string) error {
	_, err := q.db.ExecContext(ctx, clearCanonicalArtifactsForRelease, releaseID)
	return err
}

const completePendingPublish = `-- name: CompletePendingPublish :exec
DELETE FROM pending_publishes WHERE id = ?1
`

func (q *Queries) CompletePendingPublish(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, completePendingPublish, id)
	return err
}

const countSuccessfulPublishRecords = `-- name: CountSuccessfulPublishRecords :one
SELECT COUNT(1)
FROM publish_records
WHERE artifact_id = ?1
  AND target_id = ?2
  AND publish_hash = ?3
  AND status = ?4
`

type CountSuccessfulPublishRecordsParams struct {
	ArtifactID  string
	TargetID    string
	PublishHash string
	Status      string
}

func (q *Queries) CountSuccessfulPublishRecords(ctx context.Context, arg CountSuccessfulPublishRecordsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSuccessfulPublishRecords,
		arg.ArtifactID,
		arg.TargetID,
		arg.PublishHash,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deactivateVolumeGroup = `-- name: DeactivateVolumeGroup :exec
UPDATE volume_editions SET active = 0 WHERE series_id = ?1 AND group_id = ?2
`

type DeactivateVolumeGroupParams struct {
	SeriesID string
	GroupID  string
}

func (q *Queries) DeactivateVolumeGroup(ctx context.Context, arg DeactivateVolumeGroupParams) error {
	_, err := q.db.ExecContext(ctx, deactivateVolumeGroup, arg.SeriesID, arg.GroupID)
	return err
}

const dismissDiscoveryCandidate = `-- name: DismissDiscoveryCandidate :execrows
UPDATE discovery_candidates SET status='resolved', dismissal_reason=?, dismissed_fingerprint=evidence_fingerprint WHERE id=?
`

type DismissDiscoveryCandidateParams struct {
	DismissalReason string
	ID              string
}

func (q *Queries) DismissDiscoveryCandidate(ctx context.Context, arg DismissDiscoveryCandidateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, dismissDiscoveryCandidate, arg.DismissalReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, release_id, track_id, artifact_kind, is_canonical, filename, mime_type, sha256, storage_ref, built_at, state, metadata_ref, normalized_ref, raw_ref
FROM artifacts
WHERE id = ?1
`

func (q *Queries) GetArtifact(ctx context.Context, id string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.TrackID,
		&i.ArtifactKind,
		&i.IsCanonical,
		&i.Filename,
		&i.MimeType,
		&i.Sha256,
		&i.StorageRef,
		&i.BuiltAt,
		&i.State,
		&i.MetadataRef,
		&i.NormalizedRef,
		&i.RawRef,
	)
	return i, err
}

const getCanonicalArtifactByReleaseID = `-- name: GetCanonicalArtifactByReleaseID :one
SELECT id, release_id, track_id, artifact_kind, is_canonical, filename, mime_type, sha256, storage_ref, built_at, state, metadata_ref, normalized_ref, raw_ref
FROM artifacts
WHERE release_id = ?1 AND is_canonical = 1
ORDER BY built_at DESC
LIMIT 1
`

func (q *Queries) GetCanonicalArtifactByReleaseID(ctx context.Context, releaseID string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getCanonicalArtifactByReleaseID, releaseID)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.TrackID,
		&i.ArtifactKind,
		&i.IsCanonical,
		&i.Filename,
		&i.MimeType,
		&i.Sha256,
		&i.StorageRef,
		&i.BuiltAt,
		&i.State,
		&i.MetadataRef,
		&i.NormalizedRef,
		&i.RawRef,
	)
	return i, err
}

const getPendingPublish = `-- name: GetPendingPublish :one
SELECT id, target_id, payload_ref FROM pending_publishes WHERE target_id = ?1
`

func (q *Queries) GetPendingPublish(ctx context.Context, targetID string) (PendingPublish, error) {
	row := q.db.QueryRowContext(ctx, getPendingPublish, targetID)
	var i PendingPublish
	err := row.Scan(&i.ID, &i.TargetID, &i.PayloadRef)
	return i, err
}

const getPublishFilename = `-- name: GetPublishFilename :one
SELECT filename FROM publish_filenames WHERE artifact_id = ?1 AND target_id = ?2 AND publish_hash = ?3
`

type GetPublishFilenameParams struct {
	ArtifactID  string
	TargetID    string
	PublishHash string
}

func (q *Queries) GetPublishFilename(ctx context.Context, arg GetPublishFilenameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPublishFilename, arg.ArtifactID, arg.TargetID, arg.PublishHash)
	var filename string
	err := row.Scan(&filename)
	return filename, err
}

const getRelease = `-- name: GetRelease :one
SELECT id, source_id, provider_release_id, url, title, published_at, edited_at, post_type, visibility_state, normalized_payload_ref, raw_payload_ref, content_hash, discovered_at, status
FROM releases
WHERE id = ?1
`

func (q *Queries) GetRelease(ctx context.Context, id string) (Release, error) {
	row := q.db.QueryRowContext(ctx, getRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ProviderReleaseID,
		&i.Url,
		&i.Title,
		&i.PublishedAt,
		&i.EditedAt,
		&i.PostType,
		&i.VisibilityState,
		&i.NormalizedPayloadRef,
		&i.RawPayloadRef,
		&i.ContentHash,
		&i.DiscoveredAt,
		&i.Status,
	)
	return i, err
}

const getReleaseAssignment = `-- name: GetReleaseAssignment :one
SELECT release_id, track_id, rule_id, release_role, confidence
FROM release_assignments
WHERE release_id = ?1
`

func (q *Queries) GetReleaseAssignment(ctx context.Context, releaseID string) (ReleaseAssignment, error) {
	row := q.db.QueryRowContext(ctx, getReleaseAssignment, releaseID)
	var i ReleaseAssignment
	err := row.Scan(
		&i.ReleaseID,
		&i.TrackID,
		&i.RuleID,
		&i.ReleaseRole,
		&i.Confidence,
	)
	return i, err
}

const getReleaseByProviderID = `-- name: GetReleaseByProviderID :one
SELECT id, source_id, provider_release_id, url, title, published_at, edited_at, post_type, visibility_state, normalized_payload_ref, raw_payload_ref, content_hash, discovered_at, status
FROM releases
WHERE source_id = ?1 AND provider_release_id = ?2
`

type GetReleaseByProviderIDParams struct {
	SourceID          string
	ProviderReleaseID string
}

func (q *Queries) GetReleaseByProviderID(ctx context.Context, arg GetReleaseByProviderIDParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, getReleaseByProviderID, arg.SourceID, arg.ProviderReleaseID)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ProviderReleaseID,
		&i.Url,
		&i.Title,
		&i.PublishedAt,
		&i.EditedAt,
		&i.PostType,
		&i.VisibilityState,
		&i.NormalizedPayloadRef,
		&i.RawPayloadRef,
		&i.ContentHash,
		&i.DiscoveredAt,
		&i.Status,
	)
	return i, err
}

const getReleaseEnrichment = `-- name: GetReleaseEnrichment :one
SELECT metadata FROM release_enrichment WHERE source_id = ? AND provider_release_id = ? AND capture_fingerprint = ?
`

type GetReleaseEnrichmentParams struct {
	SourceID           string
	ProviderReleaseID  string
	CaptureFingerprint string
}

func (q *Queries) GetReleaseEnrichment(ctx context.Context, arg GetReleaseEnrichmentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getReleaseEnrichment, arg.SourceID, arg.ProviderReleaseID, arg.CaptureFingerprint)
	var metadata string
	err := row.Scan(&metadata)
	return metadata, err
}

const getRunRecord = `-- name: GetRunRecord :one
SELECT id, command, started_at, finished_at, status, summary, source_scope, dry_run
FROM run_records
WHERE id = ?1
`

func (q *Queries) GetRunRecord(ctx context.Context, id string) (RunRecord, error) {
	row := q.db.QueryRowContext(ctx, getRunRecord, id)
	var i RunRecord
	err := row.Scan(
		&i.ID,
		&i.Command,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Summary,
		&i.SourceScope,
		&i.DryRun,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT id, provider, source_url, source_type, creator_id, creator_name, auth_profile_id, enabled, sync_cursor, last_synced_at
FROM sources
WHERE id = ?1
`

func (q *Queries) GetSource(ctx context.Context, id string) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.SourceUrl,
		&i.SourceType,
		&i.CreatorID,
		&i.CreatorName,
		&i.AuthProfileID,
		&i.Enabled,
		&i.SyncCursor,
		&i.LastSyncedAt,
	)
	return i, err
}

const getTrack = `-- name: GetTrack :one
SELECT id, source_id, track_key, track_name, canonical_author, series_meta, output_policy, created_at, updated_at
FROM story_tracks
WHERE id = ?1
`

func (q *Queries) GetTrack(ctx context.Context, id string) (StoryTrack, error) {
	row := q.db.QueryRowContext(ctx, getTrack, id)
	var i StoryTrack
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TrackKey,
		&i.TrackName,
		&i.CanonicalAuthor,
		&i.SeriesMeta,
		&i.OutputPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrackBySourceAndKey = `-- name: GetTrackBySourceAndKey :one
SELECT id, source_id, track_key, track_name, canonical_author, series_meta, output_policy, created_at, updated_at
FROM story_tracks
WHERE source_id = ?1 AND track_key = ?2
`

type GetTrackBySourceAndKeyParams struct {
	SourceID string
	TrackKey string
}

func (q *Queries) GetTrackBySourceAndKey(ctx context.Context, arg GetTrackBySourceAndKeyParams) (StoryTrack, error) {
	row := q.db.QueryRowContext(ctx, getTrackBySourceAndKey, arg.SourceID, arg.TrackKey)
	var i StoryTrack
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TrackKey,
		&i.TrackName,
		&i.CanonicalAuthor,
		&i.SeriesMeta,
		&i.OutputPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRunRecord = `-- name: InsertRunRecord :exec
INSERT INTO run_records (id, command, started_at, finished_at, status, summary, source_scope, dry_run)
VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8
)
`

type InsertRunRecordParams struct {
	ID          string
	Command     string
	StartedAt   string
	FinishedAt  sql.NullString
	Status      string
	Summary     string
	SourceScope string
	DryRun      int64
}

func (q *Queries) InsertRunRecord(ctx context.Context, arg InsertRunRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertRunRecord,
		arg.ID,
		arg.Command,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Status,
		arg.Summary,
		arg.SourceScope,
		arg.DryRun,
	)
	return err
}

const insertVolumeEdition = `-- name: InsertVolumeEdition :exec
INSERT INTO volume_editions (id, series_id, source_id, track_id, group_id, first_chapter, last_chapter, recipe_hash, artifact_id, active)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, 1)
ON CONFLICT(id) DO UPDATE SET active = 1
`

type InsertVolumeEditionParams struct {
	ID           string
	SeriesID     string
	SourceID     string
	TrackID      string
	GroupID      string
	FirstChapter int64
	LastChapter  int64
	RecipeHash   string
	ArtifactID   string
}

func (q *Queries) InsertVolumeEdition(ctx context.Context, arg InsertVolumeEditionParams) error {
	_, err := q.db.ExecContext(ctx, insertVolumeEdition,
		arg.ID,
		arg.SeriesID,
		arg.SourceID,
		arg.TrackID,
		arg.GroupID,
		arg.FirstChapter,
		arg.LastChapter,
		arg.RecipeHash,
		arg.ArtifactID,
	)
	return err
}

const insertVolumeMember = `-- name: InsertVolumeMember :exec
INSERT INTO volume_members (edition_id, release_id, content_hash, position)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(edition_id, release_id) DO UPDATE SET content_hash = excluded.content_hash, position = excluded.position
`

type InsertVolumeMemberParams struct {
	EditionID   string
	ReleaseID   string
	ContentHash string
	Position    int64
}

func (q *Queries) InsertVolumeMember(ctx context.Context, arg InsertVolumeMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertVolumeMember,
		arg.EditionID,
		arg.ReleaseID,
		arg.ContentHash,
		arg.Position,
	)
	return err
}

const listArtifactsByReleaseID = `-- name: ListArtifactsByReleaseID :many
SELECT id, release_id, track_id, artifact_kind, is_canonical, filename, mime_type, sha256, storage_ref, built_at, state, metadata_ref, normalized_ref, raw_ref
FROM artifacts
WHERE release_id = ?1
ORDER BY built_at DESC
`

func (q *Queries) ListArtifactsByReleaseID(ctx context.Context, releaseID string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByReleaseID, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.TrackID,
			&i.ArtifactKind,
			&i.IsCanonical,
			&i.Filename,
			&i.MimeType,
			&i.Sha256,
			&i.StorageRef,
			&i.BuiltAt,
			&i.State,
			&i.MetadataRef,
			&i.NormalizedRef,
			&i.RawRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveryCandidates = `-- name: ListDiscoveryCandidates :many
SELECT id, source_id, kind, correlation_key, member_release_ids, member_fingerprints, first_observed, last_evidence_change, evidence_fingerprint, extractor_version, status, dismissal_reason, dismissed_fingerprint, last_reported_fingerprint, evidence FROM discovery_candidates WHERE (?1 = '' OR source_id = ?1) ORDER BY first_observed, id
`

func (q *Queries) ListDiscoveryCandidates(ctx context.Context, sourceID interface{}) ([]DiscoveryCandidate, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveryCandidates, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryCandidate
	for rows.Next() {
		var i DiscoveryCandidate
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Kind,
			&i.CorrelationKey,
			&i.MemberReleaseIds,
			&i.MemberFingerprints,
			&i.FirstObserved,
			&i.LastEvidenceChange,
			&i.EvidenceFingerprint,
			&i.ExtractorVersion,
			&i.Status,
			&i.DismissalReason,
			&i.DismissedFingerprint,
			&i.LastReportedFingerprint,
			&i.Evidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelObservations = `-- name: ListLabelObservations :many
SELECT provider, campaign, resource_type, resource_id, name FROM label_observations ORDER BY provider, campaign, resource_type, resource_id, name
`

func (q *Queries) ListLabelObservations(ctx context.Context) ([]LabelObservation, error) {
	rows, err := q.db.QueryContext(ctx, listLabelObservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabelObservation
	for rows.Next() {
		var i LabelObservation
		if err := rows.Scan(
			&i.Provider,
			&i.Campaign,
			&i.ResourceType,
			&i.ResourceID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishCandidates = `-- name: ListPublishCandidates :many
SELECT
  s.id, s.provider, s.source_url, s.source_type, s.creator_id, s.creator_name, s.auth_profile_id, s.enabled, s.sync_cursor, s.last_synced_at,
  t.id, t.source_id, t.track_key, t.track_name, t.canonical_author, t.series_meta, t.output_policy, t.created_at, t.updated_at,
  r.id, r.source_id, r.provider_release_id, r.url, r.title, r.published_at, r.edited_at, r.post_type, r.visibility_state, r.normalized_payload_ref, r.raw_payload_ref, r.content_hash, r.discovered_at, r.status,
  a.release_id, a.track_id, a.rule_id, a.release_role, a.confidence,
  art.id, art.release_id, art.track_id, art.artifact_kind, art.is_canonical, art.filename, art.mime_type, art.sha256, art.storage_ref, art.built_at, art.state, art.metadata_ref, art.normalized_ref, art.raw_ref
FROM artifacts art
JOIN releases r ON r.id = art.release_id
JOIN sources s ON s.id = r.source_id
LEFT JOIN release_assignments a ON a.release_id = r.id
LEFT JOIN story_tracks t ON t.id = a.track_id
WHERE art.is_canonical = 1
  AND (?1 = '' OR s.id = ?1)
ORDER BY s.id, t.track_key, r.published_at
`

type ListPublishCandidatesRow struct {
	ID                   string
	Provider             string
	SourceUrl            string
	SourceType           string
	CreatorID            string
	CreatorName          string
	AuthProfileID        string
	Enabled              int64
	SyncCursor           string
	LastSyncedAt         string
	ID_2                 sql.NullString
	SourceID             sql.NullString
	TrackKey             sql.NullString
	TrackName            sql.NullString
	CanonicalAuthor      sql.NullString
	SeriesMeta           sql.NullString
	OutputPolicy         sql.NullString
	CreatedAt            sql.NullString
	UpdatedAt            sql.NullString
	ID_3                 string
	SourceID_2           string
	ProviderReleaseID    string
	Url                  string
	Title                string
	PublishedAt          string
	EditedAt             string
	PostType             string
	VisibilityState      string
	NormalizedPayloadRef string
	RawPayloadRef        string
	ContentHash          string
	DiscoveredAt         string
	Status               string
	ReleaseID            sql.NullString
	TrackID              sql.NullString
	RuleID               sql.NullString
	ReleaseRole          sql.NullString
	Confidence           sql.NullFloat64
	ID_4                 string
	ReleaseID_2          string
	TrackID_2            string
	ArtifactKind         string
	IsCanonical          int64
	Filename             string
	MimeType             string
	Sha256               string
	StorageRef           string
	BuiltAt              string
	State                string
	MetadataRef          string
	NormalizedRef        string
	RawRef               string
}

func (q *Queries) ListPublishCandidates(ctx context.Context, sourceID interface{}) ([]ListPublishCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishCandidates, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishCandidatesRow
	for rows.Next() {
		var i ListPublishCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.SourceUrl,
			&i.SourceType,
			&i.CreatorID,
			&i.CreatorName,
			&i.AuthProfileID,
			&i.Enabled,
			&i.SyncCursor,
			&i.LastSyncedAt,
			&i.ID_2,
			&i.SourceID,
			&i.TrackKey,
			&i.TrackName,
			&i.CanonicalAuthor,
			&i.SeriesMeta,
			&i.OutputPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_3,
			&i.SourceID_2,
			&i.ProviderReleaseID,
			&i.Url,
			&i.Title,
			&i.PublishedAt,
			&i.EditedAt,
			&i.PostType,
			&i.VisibilityState,
			&i.NormalizedPayloadRef,
			&i.RawPayloadRef,
			&i.ContentHash,
			&i.DiscoveredAt,
			&i.Status,
			&i.ReleaseID,
			&i.TrackID,
			&i.RuleID,
			&i.ReleaseRole,
			&i.Confidence,
			&i.ID_4,
			&i.ReleaseID_2,
			&i.TrackID_2,
			&i.ArtifactKind,
			&i.IsCanonical,
			&i.Filename,
			&i.MimeType,
			&i.Sha256,
			&i.StorageRef,
			&i.BuiltAt,
			&i.State,
			&i.MetadataRef,
			&i.NormalizedRef,
			&i.RawRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishRecords = `-- name: ListPublishRecords :many
SELECT
  pr.id, pr.artifact_id, pr.target_id, pr.target_kind, pr.target_ref, pr.publish_hash, pr.published_at, pr.status, pr.message,
  art.id, art.release_id, art.track_id, art.artifact_kind, art.is_canonical, art.filename, art.mime_type, art.sha256, art.storage_ref, art.built_at, art.state, art.metadata_ref, art.normalized_ref, art.raw_ref,
  r.id, r.source_id, r.provider_release_id, r.url, r.title, r.published_at, r.edited_at, r.post_type, r.visibility_state, r.normalized_payload_ref, r.raw_payload_ref, r.content_hash, r.discovered_at, r.status,
  s.id, s.provider, s.source_url, s.source_type, s.creator_id, s.creator_name, s.auth_profile_id, s.enabled, s.sync_cursor, s.last_synced_at,
  t.id, t.source_id, t.track_key, t.track_name, t.canonical_author, t.series_meta, t.output_policy, t.created_at, t.updated_at
FROM publish_records pr
JOIN artifacts art ON art.id = pr.artifact_id
JOIN releases r ON r.id = art.release_id
JOIN sources s ON s.id = r.source_id
LEFT JOIN story_tracks t ON t.id = art.track_id
WHERE (?1 = '' OR s.id = ?1)
  AND (?2 = '' OR pr.target_id = ?2)
ORDER BY pr.published_at DESC, pr.id DESC
`

type ListPublishRecordsParams struct {
	SourceID interface{}
	TargetID interface{}
}

type ListPublishRecordsRow struct {
	ID                   string
	ArtifactID           string
	TargetID             string
	TargetKind           string
	TargetRef            string
	PublishHash          string
	PublishedAt          string
	Status               string
	Message              string
	ID_2                 string
	ReleaseID            string
	TrackID              string
	ArtifactKind         string
	IsCanonical          int64
	Filename             string
	MimeType             string
	Sha256               string
	StorageRef           string
	BuiltAt              string
	State                string
	MetadataRef          string
	NormalizedRef        string
	RawRef               string
	ID_3                 string
	SourceID             string
	ProviderReleaseID    string
	Url                  string
	Title                string
	PublishedAt_2        string
	EditedAt             string
	PostType             string
	VisibilityState      string
	NormalizedPayloadRef string
	RawPayloadRef        string
	ContentHash          string
	DiscoveredAt         string
	Status_2             string
	ID_4                 string
	Provider             string
	SourceUrl            string
	SourceType           string
	CreatorID            string
	CreatorName          string
	AuthProfileID        string
	Enabled              int64
	SyncCursor           string
	LastSyncedAt         string
	ID_5                 sql.NullString
	SourceID_2           sql.NullString
	TrackKey             sql.NullString
	TrackName            sql.NullString
	CanonicalAuthor      sql.NullString
	SeriesMeta           sql.NullString
	OutputPolicy         sql.NullString
	CreatedAt            sql.NullString
	UpdatedAt            sql.NullString
}

func (q *Queries) ListPublishRecords(ctx context.Context, arg ListPublishRecordsParams) ([]ListPublishRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishRecords, arg.SourceID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishRecordsRow
	for rows.Next() {
		var i ListPublishRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.TargetID,
			&i.TargetKind,
			&i.TargetRef,
			&i.PublishHash,
			&i.PublishedAt,
			&i.Status,
			&i.Message,
			&i.ID_2,
			&i.ReleaseID,
			&i.TrackID,
			&i.ArtifactKind,
			&i.IsCanonical,
			&i.Filename,
			&i.MimeType,
			&i.Sha256,
			&i.StorageRef,
			&i.BuiltAt,
			&i.State,
			&i.MetadataRef,
			&i.NormalizedRef,
			&i.RawRef,
			&i.ID_3,
			&i.SourceID,
			&i.ProviderReleaseID,
			&i.Url,
			&i.Title,
			&i.PublishedAt_2,
			&i.EditedAt,
			&i.PostType,
			&i.VisibilityState,
			&i.NormalizedPayloadRef,
			&i.RawPayloadRef,
			&i.ContentHash,
			&i.DiscoveredAt,
			&i.Status_2,
			&i.ID_4,
			&i.Provider,
			&i.SourceUrl,
			&i.SourceType,
			&i.CreatorID,
			&i.CreatorName,
			&i.AuthProfileID,
			&i.Enabled,
			&i.SyncCursor,
			&i.LastSyncedAt,
			&i.ID_5,
			&i.SourceID_2,
			&i.TrackKey,
			&i.TrackName,
			&i.CanonicalAuthor,
			&i.SeriesMeta,
			&i.OutputPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesBySource = `-- name: ListReleasesBySource :many
SELECT id, source_id, provider_release_id, url, title, published_at, edited_at, post_type, visibility_state, normalized_payload_ref, raw_payload_ref, content_hash, discovered_at, status
FROM releases
WHERE source_id = ?1
ORDER BY published_at DESC
`

func (q *Queries) ListReleasesBySource(ctx context.Context, sourceID string) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, listReleasesBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ProviderReleaseID,
			&i.Url,
			&i.Title,
			&i.PublishedAt,
			&i.EditedAt,
			&i.PostType,
			&i.VisibilityState,
			&i.NormalizedPayloadRef,
			&i.RawPayloadRef,
			&i.ContentHash,
			&i.DiscoveredAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunRecordsRecent = `-- name: ListRunRecordsRecent :many
SELECT id, command, started_at, finished_at, status, summary, source_scope, dry_run
FROM run_records
ORDER BY started_at DESC, id DESC
LIMIT ?1
`

func (q *Queries) ListRunRecordsRecent(ctx context.Context, limit int64) ([]RunRecord, error) {
	rows, err := q.db.QueryContext(ctx, listRunRecordsRecent, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunRecord
	for rows.Next() {
		var i RunRecord
		if err := rows.Scan(
			&i.ID,
			&i.Command,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Summary,
			&i.SourceScope,
			&i.DryRun,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracks = `-- name: ListTracks :many
SELECT id, source_id, track_key, track_name, canonical_author, series_meta, output_policy, created_at, updated_at
FROM story_tracks
ORDER BY source_id, track_key
`

func (q *Queries) ListTracks(ctx context.Context) ([]StoryTrack, error) {
	rows, err := q.db.QueryContext(ctx, listTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoryTrack
	for rows.Next() {
		var i StoryTrack
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TrackKey,
			&i.TrackName,
			&i.CanonicalAuthor,
			&i.SeriesMeta,
			&i.OutputPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksBySource = `-- name: ListTracksBySource :many
SELECT id, source_id, track_key, track_name, canonical_author, series_meta, output_policy, created_at, updated_at
FROM story_tracks
WHERE source_id = ?1
ORDER BY source_id, track_key
`

func (q *Queries) ListTracksBySource(ctx context.Context, sourceID string) ([]StoryTrack, error) {
	rows, err := q.db.QueryContext(ctx, listTracksBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoryTrack
	for rows.Next() {
		var i StoryTrack
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TrackKey,
			&i.TrackName,
			&i.CanonicalAuthor,
			&i.SeriesMeta,
			&i.OutputPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumeEditions = `-- name: ListVolumeEditions :many
SELECT id, series_id, source_id, track_id, group_id, first_chapter, last_chapter, recipe_hash, artifact_id, active FROM volume_editions ORDER BY series_id, first_chapter, id
`

func (q *Queries) ListVolumeEditions(ctx context.Context) ([]VolumeEdition, error) {
	rows, err := q.db.QueryContext(ctx, listVolumeEditions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VolumeEdition
	for rows.Next() {
		var i VolumeEdition
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.SourceID,
			&i.TrackID,
			&i.GroupID,
			&i.FirstChapter,
			&i.LastChapter,
			&i.RecipeHash,
			&i.ArtifactID,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumeMembers = `-- name: ListVolumeMembers :many
SELECT release_id, content_hash, position FROM volume_members WHERE edition_id = ?1 ORDER BY position, release_id
`

type ListVolumeMembersRow struct {
	ReleaseID   string
	ContentHash string
	Position    int64
}

func (q *Queries) ListVolumeMembers(ctx context.Context, editionID string) ([]ListVolumeMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listVolumeMembers, editionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVolumeMembersRow
	for rows.Next() {
		var i ListVolumeMembersRow
		if err := rows.Scan(&i.ReleaseID, &i.ContentHash, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumePublishRecords = `-- name: ListVolumePublishRecords :many
SELECT DISTINCT pr.id, pr.artifact_id, pr.target_id, pr.target_kind, pr.target_ref, pr.publish_hash, pr.published_at, pr.status, pr.message FROM publish_records pr JOIN volume_editions v ON v.artifact_id = pr.artifact_id ORDER BY pr.published_at DESC
`

func (q *Queries) ListVolumePublishRecords(ctx context.Context) ([]PublishRecord, error) {
	rows, err := q.db.QueryContext(ctx, listVolumePublishRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublishRecord
	for rows.Next() {
		var i PublishRecord
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.TargetID,
			&i.TargetKind,
			&i.TargetRef,
			&i.PublishHash,
			&i.PublishedAt,
			&i.Status,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseLease = `-- name: ReleaseLease :exec
DELETE FROM leases
WHERE key = ?1 AND holder = ?2
`

type ReleaseLeaseParams struct {
	Key    string
	Holder string
}

func (q *Queries) ReleaseLease(ctx context.Context, arg ReleaseLeaseParams) error {
	_, err := q.db.ExecContext(ctx, releaseLease, arg.Key, arg.Holder)
	return err
}

const saveLabelObservation = `-- name: SaveLabelObservation :exec
INSERT OR IGNORE INTO label_observations (provider, campaign, resource_type, resource_id, name) VALUES (?, ?, ?, ?, ?)
`

type SaveLabelObservationParams struct {
	Provider     string
	Campaign     string
	ResourceType string
	ResourceID   string
	Name         string
}

func (q *Queries) SaveLabelObservation(ctx context.Context, arg SaveLabelObservationParams) error {
	_, err := q.db.ExecContext(ctx, saveLabelObservation,
		arg.Provider,
		arg.Campaign,
		arg.ResourceType,
		arg.ResourceID,
		arg.Name,
	)
	return err
}

const savePendingPublish = `-- name: SavePendingPublish :exec
INSERT INTO pending_publishes (id, target_id, payload_ref) VALUES (?1, ?2, ?3)
`

type SavePendingPublishParams struct {
	ID         string
	TargetID   string
	PayloadRef string
}

func (q *Queries) SavePendingPublish(ctx context.Context, arg SavePendingPublishParams) error {
	_, err := q.db.ExecContext(ctx, savePendingPublish, arg.ID, arg.TargetID, arg.PayloadRef)
	return err
}

const savePublishFilename = `-- name: SavePublishFilename :exec
INSERT INTO publish_filenames (artifact_id, target_id, publish_hash, filename)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(artifact_id, target_id, publish_hash) DO UPDATE SET filename = excluded.filename
`

type SavePublishFilenameParams struct {
	ArtifactID  string
	TargetID    string
	PublishHash string
	Filename    string
}

func (q *Queries) SavePublishFilename(ctx context.Context, arg SavePublishFilenameParams) error {
	_, err := q.db.ExecContext(ctx, savePublishFilename,
		arg.ArtifactID,
		arg.TargetID,
		arg.PublishHash,
		arg.Filename,
	)
	return err
}

const updateRunRecord = `-- name: UpdateRunRecord :exec
UPDATE run_records
SET finished_at = ?1, status = ?2, summary = ?3
WHERE id = ?4
`

type UpdateRunRecordParams struct {
	FinishedAt sql.NullString
	Status     string
	Summary    string
	ID         string
}

func (q *Queries) UpdateRunRecord(ctx context.Context, arg UpdateRunRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateRunRecord,
		arg.FinishedAt,
		arg.Status,
		arg.Summary,
		arg.ID,
	)
	return err
}

const updateSourceLastSyncedAt = `-- name: UpdateSourceLastSyncedAt :exec
UPDATE sources
SET last_synced_at = ?1
WHERE id = ?2
`

type UpdateSourceLastSyncedAtParams struct {
	LastSyncedAt string
	ID           string
}

func (q *Queries) UpdateSourceLastSyncedAt(ctx context.Context, arg UpdateSourceLastSyncedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateSourceLastSyncedAt, arg.LastSyncedAt, arg.ID)
	return err
}

const upsertArtifact = `-- name: UpsertArtifact :exec
INSERT INTO artifacts (
  id, release_id, track_id, artifact_kind, is_canonical, filename, mime_type,
  sha256, storage_ref, built_at, state, metadata_ref, normalized_ref, raw_ref
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9, ?10, ?11, ?12,
  ?13, ?14
)
ON CONFLICT(release_id, sha256, artifact_kind, filename, track_id) DO UPDATE SET
  track_id = excluded.track_id,
  is_canonical = excluded.is_canonical,
  filename = excluded.filename,
  mime_type = excluded.mime_type,
  storage_ref = excluded.storage_ref,
  built_at = excluded.built_at,
  state = excluded.state,
  metadata_ref = excluded.metadata_ref,
  normalized_ref = excluded.normalized_ref,
  raw_ref = excluded.raw_ref
`

type UpsertArtifactParams struct {
	ID            string
	ReleaseID     string
	TrackID       string
	ArtifactKind  string
	IsCanonical   int64
	Filename      string
	MimeType      string
	Sha256        string
	StorageRef    string
	BuiltAt       string
	State         string
	MetadataRef   string
	NormalizedRef string
	RawRef        string
}

func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) error {
	_, err := q.db.ExecContext(ctx, upsertArtifact,
		arg.ID,
		arg.ReleaseID,
		arg.TrackID,
		arg.ArtifactKind,
		arg.IsCanonical,
		arg.Filename,
		arg.MimeType,
		arg.Sha256,
		arg.StorageRef,
		arg.BuiltAt,
		arg.State,
		arg.MetadataRef,
		arg.NormalizedRef,
		arg.RawRef,
	)
	return err
}

const upsertDiscoveryCandidate = `-- name: UpsertDiscoveryCandidate :exec
INSERT INTO discovery_candidates (id, source_id, kind, correlation_key, member_release_ids, member_fingerprints, first_observed, last_evidence_change, evidence_fingerprint, extractor_version, status, dismissal_reason, dismissed_fingerprint, last_reported_fingerprint, evidence)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  kind=excluded.kind, correlation_key=excluded.correlation_key, member_release_ids=excluded.member_release_ids, member_fingerprints=excluded.member_fingerprints,
  last_evidence_change=excluded.last_evidence_change, evidence_fingerprint=excluded.evidence_fingerprint,
  extractor_version=excluded.extractor_version, status=excluded.status, dismissal_reason=excluded.dismissal_reason,
  dismissed_fingerprint=excluded.dismissed_fingerprint, last_reported_fingerprint=excluded.last_reported_fingerprint, evidence=excluded.evidence
`

type UpsertDiscoveryCandidateParams struct {
	ID                      string
	SourceID                string
	Kind                    string
	CorrelationKey          string
	MemberReleaseIds        string
	MemberFingerprints      string
	FirstObserved           string
	LastEvidenceChange      string
	EvidenceFingerprint     string
	ExtractorVersion        int64
	Status                  string
	DismissalReason         string
	DismissedFingerprint    string
	LastReportedFingerprint string
	Evidence                string
}

func (q *Queries) UpsertDiscoveryCandidate(ctx context.Context, arg UpsertDiscoveryCandidateParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoveryCandidate,
		arg.ID,
		arg.SourceID,
		arg.Kind,
		arg.CorrelationKey,
		arg.MemberReleaseIds,
		arg.MemberFingerprints,
		arg.FirstObserved,
		arg.LastEvidenceChange,
		arg.EvidenceFingerprint,
		arg.ExtractorVersion,
		arg.Status,
		arg.DismissalReason,
		arg.DismissedFingerprint,
		arg.LastReportedFingerprint,
		arg.Evidence,
	)
	return err
}

const upsertPublishRecord = `-- name: UpsertPublishRecord :exec
INSERT INTO publish_records (id, artifact_id, target_id, target_kind, target_ref, publish_hash, published_at, status, message)
VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9
)
ON CONFLICT(artifact_id, target_id, publish_hash) DO UPDATE SET
  target_kind = excluded.target_kind,
  target_ref = excluded.target_ref,
  published_at = excluded.published_at,
  status = excluded.status,
  message = excluded.message
`

type UpsertPublishRecordParams struct {
	ID          string
	ArtifactID  string
	TargetID    string
	TargetKind  string
	TargetRef   string
	PublishHash string
	PublishedAt string
	Status      string
	Message     string
}

func (q *Queries) UpsertPublishRecord(ctx context.Context, arg UpsertPublishRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertPublishRecord,
		arg.ID,
		arg.ArtifactID,
		arg.TargetID,
		arg.TargetKind,
		arg.TargetRef,
		arg.PublishHash,
		arg.PublishedAt,
		arg.Status,
		arg.Message,
	)
	return err
}

const upsertRelease = `-- name: UpsertRelease :exec
INSERT INTO releases (
  id, source_id, provider_release_id, url, title, published_at, edited_at,
  post_type, visibility_state, normalized_payload_ref, raw_payload_ref,
  content_hash, discovered_at, status
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9, ?10, ?11,
  ?12, ?13, ?14
)
ON CONFLICT(source_id, provider_release_id) DO UPDATE SET
  url = excluded.url,
  title = excluded.title,
  published_at = excluded.published_at,
  edited_at = excluded.edited_at,
  post_type = excluded.post_type,
  visibility_state = excluded.visibility_state,
  normalized_payload_ref = excluded.normalized_payload_ref,
  raw_payload_ref = excluded.raw_payload_ref,
  content_hash = excluded.content_hash,
  discovered_at = excluded.discovered_at,
  status = excluded.status
`

type UpsertReleaseParams struct {
	ID                   string
	SourceID             string
	ProviderReleaseID    string
	Url                  string
	Title                string
	PublishedAt          string
	EditedAt             string
	PostType             string
	VisibilityState      string
	NormalizedPayloadRef string
	RawPayloadRef        string
	ContentHash          string
	DiscoveredAt         string
	Status               string
}

func (q *Queries) UpsertRelease(ctx context.Context, arg UpsertReleaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertRelease,
		arg.ID,
		arg.SourceID,
		arg.ProviderReleaseID,
		arg.Url,
		arg.Title,
		arg.PublishedAt,
		arg.EditedAt,
		arg.PostType,
		arg.VisibilityState,
		arg.NormalizedPayloadRef,
		arg.RawPayloadRef,
		arg.ContentHash,
		arg.DiscoveredAt,
		arg.Status,
	)
	return err
}

const upsertReleaseAssignment = `-- name: UpsertReleaseAssignment :exec
INSERT INTO release_assignments (release_id, track_id, rule_id, release_role, confidence)
VALUES (
  ?1, ?2, ?3, ?4, ?5
)
ON CONFLICT(release_id) DO UPDATE SET
  track_id = excluded.track_id,
  rule_id = excluded.rule_id,
  release_role = excluded.release_role,
  confidence = excluded.confidence
`

type UpsertReleaseAssignmentParams struct {
	ReleaseID   string
	TrackID     string
	RuleID      string
	ReleaseRole string
	Confidence  float64
}

func (q *Queries) UpsertReleaseAssignment(ctx context.Context, arg UpsertReleaseAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertReleaseAssignment,
		arg.ReleaseID,
		arg.TrackID,
		arg.RuleID,
		arg.ReleaseRole,
		arg.Confidence,
	)
	return err
}

const upsertReleaseEnrichment = `-- name: UpsertReleaseEnrichment :exec
INSERT INTO release_enrichment (source_id, provider_release_id, capture_fingerprint, metadata) VALUES (?, ?, ?, ?)
ON CONFLICT(source_id, provider_release_id, capture_fingerprint) DO UPDATE SET metadata = excluded.metadata
`

type UpsertReleaseEnrichmentParams struct {
	SourceID           string
	ProviderReleaseID  string
	CaptureFingerprint string
	Metadata           string
}

func (q *Queries) UpsertReleaseEnrichment(ctx context.Context, arg UpsertReleaseEnrichmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertReleaseEnrichment,
		arg.SourceID,
		arg.ProviderReleaseID,
		arg.CaptureFingerprint,
		arg.Metadata,
	)
	return err
}

const upsertSource = `-- name: UpsertSource :exec
INSERT INTO sources (
  id, provider, source_url, source_type, creator_id, creator_name,
  auth_profile_id, enabled, sync_cursor, last_synced_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10
)
ON CONFLICT(id) DO UPDATE SET
  provider = excluded.provider,
  source_url = excluded.source_url,
  source_type = excluded.source_type,
  creator_id = excluded.creator_id,
  creator_name = excluded.creator_name,
  auth_profile_id = excluded.auth_profile_id,
  enabled = excluded.enabled,
  sync_cursor = excluded.sync_cursor,
  last_synced_at = excluded.last_synced_at
`

type UpsertSourceParams struct {
	ID            string
	Provider      string
	SourceUrl     string
	SourceType    string
	CreatorID     string
	CreatorName   string
	AuthProfileID string
	Enabled       int64
	SyncCursor    string
	LastSyncedAt  string
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertSource,
		arg.ID,
		arg.Provider,
		arg.SourceUrl,
		arg.SourceType,
		arg.CreatorID,
		arg.CreatorName,
		arg.AuthProfileID,
		arg.Enabled,
		arg.SyncCursor,
		arg.LastSyncedAt,
	)
	return err
}

const upsertTrack = `-- name: UpsertTrack :exec
INSERT INTO story_tracks (
  id, source_id, track_key, track_name, canonical_author, series_meta,
  output_policy, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9
)
ON CONFLICT(source_id, track_key) DO UPDATE SET
  track_name = excluded.track_name,
  canonical_author = excluded.canonical_author,
  series_meta = excluded.series_meta,
  output_policy = excluded.output_policy,
  updated_at = excluded.updated_at
`

type UpsertTrackParams struct {
	ID              string
	SourceID        string
	TrackKey        string
	TrackName       string
	CanonicalAuthor string
	SeriesMeta      string
	OutputPolicy    string
	CreatedAt       string
	UpdatedAt       string
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.ID,
		arg.SourceID,
		arg.TrackKey,
		arg.TrackName,
		arg.CanonicalAuthor,
		arg.SeriesMeta,
		arg.OutputPolicy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
