// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const clearCanonicalArtifactsForRelease = `-- name: ClearCanonicalArtifactsForRelease :exec
UPDATE artifacts
SET is_canonical = 0
WHERE release_id = ?1
`

func (q *Queries) ClearCanonicalArtifactsForRelease(ctx context.Context, releaseID string) error {
	_, err := q.db.ExecContext(ctx, clearCanonicalArtifactsForRelease, releaseID)
	return err
}

const countSuccessfulPublishRecords = `-- name: CountSuccessfulPublishRecords :one
SELECT COUNT(1)
FROM publish_records
WHERE artifact_id = ?1
  AND target_id = ?2
  AND publish_hash = ?3
  AND status = ?4
`

type CountSuccessfulPublishRecordsParams struct {
	ArtifactID  string
	TargetID    string
	PublishHash string
	Status      string
}

func (q *Queries) CountSuccessfulPublishRecords(ctx context.Context, arg CountSuccessfulPublishRecordsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSuccessfulPublishRecords,
		arg.ArtifactID,
		arg.TargetID,
		arg.PublishHash,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, release_id, track_id, artifact_kind, is_canonical, filename, mime_type, sha256, storage_ref, built_at, state, metadata_ref, normalized_ref, raw_ref
FROM artifacts
WHERE id = ?1
`

func (q *Queries) GetArtifact(ctx context.Context, id string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.TrackID,
		&i.ArtifactKind,
		&i.IsCanonical,
		&i.Filename,
		&i.MimeType,
		&i.Sha256,
		&i.StorageRef,
		&i.BuiltAt,
		&i.State,
		&i.MetadataRef,
		&i.NormalizedRef,
		&i.RawRef,
	)
	return i, err
}

const getCanonicalArtifactByReleaseID = `-- name: GetCanonicalArtifactByReleaseID :one
SELECT id, release_id, track_id, artifact_kind, is_canonical, filename, mime_type, sha256, storage_ref, built_at, state, metadata_ref, normalized_ref, raw_ref
FROM artifacts
WHERE release_id = ?1 AND is_canonical = 1
ORDER BY built_at DESC
LIMIT 1
`

func (q *Queries) GetCanonicalArtifactByReleaseID(ctx context.Context, releaseID string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getCanonicalArtifactByReleaseID, releaseID)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.TrackID,
		&i.ArtifactKind,
		&i.IsCanonical,
		&i.Filename,
		&i.MimeType,
		&i.Sha256,
		&i.StorageRef,
		&i.BuiltAt,
		&i.State,
		&i.MetadataRef,
		&i.NormalizedRef,
		&i.RawRef,
	)
	return i, err
}

const getRelease = `-- name: GetRelease :one
SELECT id, source_id, provider_release_id, url, title, published_at, edited_at, post_type, visibility_state, normalized_payload_ref, raw_payload_ref, content_hash, discovered_at, status
FROM releases
WHERE id = ?1
`

func (q *Queries) GetRelease(ctx context.Context, id string) (Release, error) {
	row := q.db.QueryRowContext(ctx, getRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ProviderReleaseID,
		&i.Url,
		&i.Title,
		&i.PublishedAt,
		&i.EditedAt,
		&i.PostType,
		&i.VisibilityState,
		&i.NormalizedPayloadRef,
		&i.RawPayloadRef,
		&i.ContentHash,
		&i.DiscoveredAt,
		&i.Status,
	)
	return i, err
}

const getReleaseAssignment = `-- name: GetReleaseAssignment :one
SELECT release_id, track_id, rule_id, release_role, confidence
FROM release_assignments
WHERE release_id = ?1
`

func (q *Queries) GetReleaseAssignment(ctx context.Context, releaseID string) (ReleaseAssignment, error) {
	row := q.db.QueryRowContext(ctx, getReleaseAssignment, releaseID)
	var i ReleaseAssignment
	err := row.Scan(
		&i.ReleaseID,
		&i.TrackID,
		&i.RuleID,
		&i.ReleaseRole,
		&i.Confidence,
	)
	return i, err
}

const getReleaseByProviderID = `-- name: GetReleaseByProviderID :one
SELECT id, source_id, provider_release_id, url, title, published_at, edited_at, post_type, visibility_state, normalized_payload_ref, raw_payload_ref, content_hash, discovered_at, status
FROM releases
WHERE source_id = ?1 AND provider_release_id = ?2
`

type GetReleaseByProviderIDParams struct {
	SourceID          string
	ProviderReleaseID string
}

func (q *Queries) GetReleaseByProviderID(ctx context.Context, arg GetReleaseByProviderIDParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, getReleaseByProviderID, arg.SourceID, arg.ProviderReleaseID)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ProviderReleaseID,
		&i.Url,
		&i.Title,
		&i.PublishedAt,
		&i.EditedAt,
		&i.PostType,
		&i.VisibilityState,
		&i.NormalizedPayloadRef,
		&i.RawPayloadRef,
		&i.ContentHash,
		&i.DiscoveredAt,
		&i.Status,
	)
	return i, err
}

const getRunRecord = `-- name: GetRunRecord :one
SELECT id, command, started_at, finished_at, status, summary, source_scope, dry_run
FROM run_records
WHERE id = ?1
`

func (q *Queries) GetRunRecord(ctx context.Context, id string) (RunRecord, error) {
	row := q.db.QueryRowContext(ctx, getRunRecord, id)
	var i RunRecord
	err := row.Scan(
		&i.ID,
		&i.Command,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Summary,
		&i.SourceScope,
		&i.DryRun,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT id, provider, source_url, source_type, creator_id, creator_name, auth_profile_id, enabled, sync_cursor, last_synced_at
FROM sources
WHERE id = ?1
`

func (q *Queries) GetSource(ctx context.Context, id string) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.SourceUrl,
		&i.SourceType,
		&i.CreatorID,
		&i.CreatorName,
		&i.AuthProfileID,
		&i.Enabled,
		&i.SyncCursor,
		&i.LastSyncedAt,
	)
	return i, err
}

const getTrack = `-- name: GetTrack :one
SELECT id, source_id, track_key, track_name, canonical_author, series_meta, output_policy, created_at, updated_at
FROM story_tracks
WHERE id = ?1
`

func (q *Queries) GetTrack(ctx context.Context, id string) (StoryTrack, error) {
	row := q.db.QueryRowContext(ctx, getTrack, id)
	var i StoryTrack
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TrackKey,
		&i.TrackName,
		&i.CanonicalAuthor,
		&i.SeriesMeta,
		&i.OutputPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrackBySourceAndKey = `-- name: GetTrackBySourceAndKey :one
SELECT id, source_id, track_key, track_name, canonical_author, series_meta, output_policy, created_at, updated_at
FROM story_tracks
WHERE source_id = ?1 AND track_key = ?2
`

type GetTrackBySourceAndKeyParams struct {
	SourceID string
	TrackKey string
}

func (q *Queries) GetTrackBySourceAndKey(ctx context.Context, arg GetTrackBySourceAndKeyParams) (StoryTrack, error) {
	row := q.db.QueryRowContext(ctx, getTrackBySourceAndKey, arg.SourceID, arg.TrackKey)
	var i StoryTrack
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TrackKey,
		&i.TrackName,
		&i.CanonicalAuthor,
		&i.SeriesMeta,
		&i.OutputPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEventRecord = `-- name: InsertEventRecord :exec
INSERT INTO event_records (id, run_id, timestamp, level, component, message, entity_kind, entity_id, payload_ref)
VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9
)
`

type InsertEventRecordParams struct {
	ID         string
	RunID      string
	Timestamp  string
	Level      string
	Component  string
	Message    string
	EntityKind string
	EntityID   string
	PayloadRef string
}

func (q *Queries) InsertEventRecord(ctx context.Context, arg InsertEventRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertEventRecord,
		arg.ID,
		arg.RunID,
		arg.Timestamp,
		arg.Level,
		arg.Component,
		arg.Message,
		arg.EntityKind,
		arg.EntityID,
		arg.PayloadRef,
	)
	return err
}

const insertRunRecord = `-- name: InsertRunRecord :exec
INSERT INTO run_records (id, command, started_at, finished_at, status, summary, source_scope, dry_run)
VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8
)
`

type InsertRunRecordParams struct {
	ID          string
	Command     string
	StartedAt   string
	FinishedAt  sql.NullString
	Status      string
	Summary     string
	SourceScope string
	DryRun      int64
}

func (q *Queries) InsertRunRecord(ctx context.Context, arg InsertRunRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertRunRecord,
		arg.ID,
		arg.Command,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Status,
		arg.Summary,
		arg.SourceScope,
		arg.DryRun,
	)
	return err
}

const listArtifactsByReleaseID = `-- name: ListArtifactsByReleaseID :many
SELECT id, release_id, track_id, artifact_kind, is_canonical, filename, mime_type, sha256, storage_ref, built_at, state, metadata_ref, normalized_ref, raw_ref
FROM artifacts
WHERE release_id = ?1
ORDER BY built_at DESC
`

func (q *Queries) ListArtifactsByReleaseID(ctx context.Context, releaseID string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByReleaseID, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.TrackID,
			&i.ArtifactKind,
			&i.IsCanonical,
			&i.Filename,
			&i.MimeType,
			&i.Sha256,
			&i.StorageRef,
			&i.BuiltAt,
			&i.State,
			&i.MetadataRef,
			&i.NormalizedRef,
			&i.RawRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByRunID = `-- name: ListEventsByRunID :many
SELECT id, run_id, timestamp, level, component, message, entity_kind, entity_id, payload_ref
FROM event_records
WHERE run_id = ?1
ORDER BY timestamp
`

func (q *Queries) ListEventsByRunID(ctx context.Context, runID string) ([]EventRecord, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventRecord
	for rows.Next() {
		var i EventRecord
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Timestamp,
			&i.Level,
			&i.Component,
			&i.Message,
			&i.EntityKind,
			&i.EntityID,
			&i.PayloadRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishCandidates = `-- name: ListPublishCandidates :many
SELECT
  s.id, s.provider, s.source_url, s.source_type, s.creator_id, s.creator_name, s.auth_profile_id, s.enabled, s.sync_cursor, s.last_synced_at,
  t.id, t.source_id, t.track_key, t.track_name, t.canonical_author, t.series_meta, t.output_policy, t.created_at, t.updated_at,
  r.id, r.source_id, r.provider_release_id, r.url, r.title, r.published_at, r.edited_at, r.post_type, r.visibility_state, r.normalized_payload_ref, r.raw_payload_ref, r.content_hash, r.discovered_at, r.status,
  a.release_id, a.track_id, a.rule_id, a.release_role, a.confidence,
  art.id, art.release_id, art.track_id, art.artifact_kind, art.is_canonical, art.filename, art.mime_type, art.sha256, art.storage_ref, art.built_at, art.state, art.metadata_ref, art.normalized_ref, art.raw_ref
FROM artifacts art
JOIN releases r ON r.id = art.release_id
JOIN sources s ON s.id = r.source_id
LEFT JOIN release_assignments a ON a.release_id = r.id
LEFT JOIN story_tracks t ON t.id = a.track_id
WHERE art.is_canonical = 1
ORDER BY s.id, t.track_key, r.published_at
`

type ListPublishCandidatesRow struct {
	ID                   string
	Provider             string
	SourceUrl            string
	SourceType           string
	CreatorID            string
	CreatorName          string
	AuthProfileID        string
	Enabled              int64
	SyncCursor           string
	LastSyncedAt         string
	ID_2                 sql.NullString
	SourceID             sql.NullString
	TrackKey             sql.NullString
	TrackName            sql.NullString
	CanonicalAuthor      sql.NullString
	SeriesMeta           sql.NullString
	OutputPolicy         sql.NullString
	CreatedAt            sql.NullString
	UpdatedAt            sql.NullString
	ID_3                 string
	SourceID_2           string
	ProviderReleaseID    string
	Url                  string
	Title                string
	PublishedAt          string
	EditedAt             string
	PostType             string
	VisibilityState      string
	NormalizedPayloadRef string
	RawPayloadRef        string
	ContentHash          string
	DiscoveredAt         string
	Status               string
	ReleaseID            sql.NullString
	TrackID              sql.NullString
	RuleID               sql.NullString
	ReleaseRole          sql.NullString
	Confidence           sql.NullFloat64
	ID_4                 string
	ReleaseID_2          string
	TrackID_2            string
	ArtifactKind         string
	IsCanonical          int64
	Filename             string
	MimeType             string
	Sha256               string
	StorageRef           string
	BuiltAt              string
	State                string
	MetadataRef          string
	NormalizedRef        string
	RawRef               string
}

func (q *Queries) ListPublishCandidates(ctx context.Context) ([]ListPublishCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishCandidatesRow
	for rows.Next() {
		var i ListPublishCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.SourceUrl,
			&i.SourceType,
			&i.CreatorID,
			&i.CreatorName,
			&i.AuthProfileID,
			&i.Enabled,
			&i.SyncCursor,
			&i.LastSyncedAt,
			&i.ID_2,
			&i.SourceID,
			&i.TrackKey,
			&i.TrackName,
			&i.CanonicalAuthor,
			&i.SeriesMeta,
			&i.OutputPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_3,
			&i.SourceID_2,
			&i.ProviderReleaseID,
			&i.Url,
			&i.Title,
			&i.PublishedAt,
			&i.EditedAt,
			&i.PostType,
			&i.VisibilityState,
			&i.NormalizedPayloadRef,
			&i.RawPayloadRef,
			&i.ContentHash,
			&i.DiscoveredAt,
			&i.Status,
			&i.ReleaseID,
			&i.TrackID,
			&i.RuleID,
			&i.ReleaseRole,
			&i.Confidence,
			&i.ID_4,
			&i.ReleaseID_2,
			&i.TrackID_2,
			&i.ArtifactKind,
			&i.IsCanonical,
			&i.Filename,
			&i.MimeType,
			&i.Sha256,
			&i.StorageRef,
			&i.BuiltAt,
			&i.State,
			&i.MetadataRef,
			&i.NormalizedRef,
			&i.RawRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishCandidatesBySource = `-- name: ListPublishCandidatesBySource :many
SELECT
  s.id, s.provider, s.source_url, s.source_type, s.creator_id, s.creator_name, s.auth_profile_id, s.enabled, s.sync_cursor, s.last_synced_at,
  t.id, t.source_id, t.track_key, t.track_name, t.canonical_author, t.series_meta, t.output_policy, t.created_at, t.updated_at,
  r.id, r.source_id, r.provider_release_id, r.url, r.title, r.published_at, r.edited_at, r.post_type, r.visibility_state, r.normalized_payload_ref, r.raw_payload_ref, r.content_hash, r.discovered_at, r.status,
  a.release_id, a.track_id, a.rule_id, a.release_role, a.confidence,
  art.id, art.release_id, art.track_id, art.artifact_kind, art.is_canonical, art.filename, art.mime_type, art.sha256, art.storage_ref, art.built_at, art.state, art.metadata_ref, art.normalized_ref, art.raw_ref
FROM artifacts art
JOIN releases r ON r.id = art.release_id
JOIN sources s ON s.id = r.source_id
LEFT JOIN release_assignments a ON a.release_id = r.id
LEFT JOIN story_tracks t ON t.id = a.track_id
WHERE art.is_canonical = 1 AND s.id = ?1
ORDER BY s.id, t.track_key, r.published_at
`

type ListPublishCandidatesBySourceRow struct {
	ID                   string
	Provider             string
	SourceUrl            string
	SourceType           string
	CreatorID            string
	CreatorName          string
	AuthProfileID        string
	Enabled              int64
	SyncCursor           string
	LastSyncedAt         string
	ID_2                 sql.NullString
	SourceID             sql.NullString
	TrackKey             sql.NullString
	TrackName            sql.NullString
	CanonicalAuthor      sql.NullString
	SeriesMeta           sql.NullString
	OutputPolicy         sql.NullString
	CreatedAt            sql.NullString
	UpdatedAt            sql.NullString
	ID_3                 string
	SourceID_2           string
	ProviderReleaseID    string
	Url                  string
	Title                string
	PublishedAt          string
	EditedAt             string
	PostType             string
	VisibilityState      string
	NormalizedPayloadRef string
	RawPayloadRef        string
	ContentHash          string
	DiscoveredAt         string
	Status               string
	ReleaseID            sql.NullString
	TrackID              sql.NullString
	RuleID               sql.NullString
	ReleaseRole          sql.NullString
	Confidence           sql.NullFloat64
	ID_4                 string
	ReleaseID_2          string
	TrackID_2            string
	ArtifactKind         string
	IsCanonical          int64
	Filename             string
	MimeType             string
	Sha256               string
	StorageRef           string
	BuiltAt              string
	State                string
	MetadataRef          string
	NormalizedRef        string
	RawRef               string
}

func (q *Queries) ListPublishCandidatesBySource(ctx context.Context, sourceID string) ([]ListPublishCandidatesBySourceRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishCandidatesBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishCandidatesBySourceRow
	for rows.Next() {
		var i ListPublishCandidatesBySourceRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.SourceUrl,
			&i.SourceType,
			&i.CreatorID,
			&i.CreatorName,
			&i.AuthProfileID,
			&i.Enabled,
			&i.SyncCursor,
			&i.LastSyncedAt,
			&i.ID_2,
			&i.SourceID,
			&i.TrackKey,
			&i.TrackName,
			&i.CanonicalAuthor,
			&i.SeriesMeta,
			&i.OutputPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_3,
			&i.SourceID_2,
			&i.ProviderReleaseID,
			&i.Url,
			&i.Title,
			&i.PublishedAt,
			&i.EditedAt,
			&i.PostType,
			&i.VisibilityState,
			&i.NormalizedPayloadRef,
			&i.RawPayloadRef,
			&i.ContentHash,
			&i.DiscoveredAt,
			&i.Status,
			&i.ReleaseID,
			&i.TrackID,
			&i.RuleID,
			&i.ReleaseRole,
			&i.Confidence,
			&i.ID_4,
			&i.ReleaseID_2,
			&i.TrackID_2,
			&i.ArtifactKind,
			&i.IsCanonical,
			&i.Filename,
			&i.MimeType,
			&i.Sha256,
			&i.StorageRef,
			&i.BuiltAt,
			&i.State,
			&i.MetadataRef,
			&i.NormalizedRef,
			&i.RawRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesBySource = `-- name: ListReleasesBySource :many
SELECT id, source_id, provider_release_id, url, title, published_at, edited_at, post_type, visibility_state, normalized_payload_ref, raw_payload_ref, content_hash, discovered_at, status
FROM releases
WHERE source_id = ?1
ORDER BY published_at DESC
`

func (q *Queries) ListReleasesBySource(ctx context.Context, sourceID string) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, listReleasesBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ProviderReleaseID,
			&i.Url,
			&i.Title,
			&i.PublishedAt,
			&i.EditedAt,
			&i.PostType,
			&i.VisibilityState,
			&i.NormalizedPayloadRef,
			&i.RawPayloadRef,
			&i.ContentHash,
			&i.DiscoveredAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, provider, source_url, source_type, creator_id, creator_name, auth_profile_id, enabled, sync_cursor, last_synced_at
FROM sources
ORDER BY id
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.SourceUrl,
			&i.SourceType,
			&i.CreatorID,
			&i.CreatorName,
			&i.AuthProfileID,
			&i.Enabled,
			&i.SyncCursor,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracks = `-- name: ListTracks :many
SELECT id, source_id, track_key, track_name, canonical_author, series_meta, output_policy, created_at, updated_at
FROM story_tracks
ORDER BY source_id, track_key
`

func (q *Queries) ListTracks(ctx context.Context) ([]StoryTrack, error) {
	rows, err := q.db.QueryContext(ctx, listTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoryTrack
	for rows.Next() {
		var i StoryTrack
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TrackKey,
			&i.TrackName,
			&i.CanonicalAuthor,
			&i.SeriesMeta,
			&i.OutputPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksBySource = `-- name: ListTracksBySource :many
SELECT id, source_id, track_key, track_name, canonical_author, series_meta, output_policy, created_at, updated_at
FROM story_tracks
WHERE source_id = ?1
ORDER BY source_id, track_key
`

func (q *Queries) ListTracksBySource(ctx context.Context, sourceID string) ([]StoryTrack, error) {
	rows, err := q.db.QueryContext(ctx, listTracksBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoryTrack
	for rows.Next() {
		var i StoryTrack
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TrackKey,
			&i.TrackName,
			&i.CanonicalAuthor,
			&i.SeriesMeta,
			&i.OutputPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunRecord = `-- name: UpdateRunRecord :exec
UPDATE run_records
SET finished_at = ?1, status = ?2, summary = ?3
WHERE id = ?4
`

type UpdateRunRecordParams struct {
	FinishedAt sql.NullString
	Status     string
	Summary    string
	ID         string
}

func (q *Queries) UpdateRunRecord(ctx context.Context, arg UpdateRunRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateRunRecord,
		arg.FinishedAt,
		arg.Status,
		arg.Summary,
		arg.ID,
	)
	return err
}

const updateSourceLastSyncedAt = `-- name: UpdateSourceLastSyncedAt :exec
UPDATE sources
SET last_synced_at = ?1
WHERE id = ?2
`

type UpdateSourceLastSyncedAtParams struct {
	LastSyncedAt string
	ID           string
}

func (q *Queries) UpdateSourceLastSyncedAt(ctx context.Context, arg UpdateSourceLastSyncedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateSourceLastSyncedAt, arg.LastSyncedAt, arg.ID)
	return err
}

const upsertArtifact = `-- name: UpsertArtifact :exec
INSERT INTO artifacts (
  id, release_id, track_id, artifact_kind, is_canonical, filename, mime_type,
  sha256, storage_ref, built_at, state, metadata_ref, normalized_ref, raw_ref
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9, ?10, ?11, ?12,
  ?13, ?14
)
ON CONFLICT(release_id, sha256, artifact_kind) DO UPDATE SET
  track_id = excluded.track_id,
  is_canonical = excluded.is_canonical,
  filename = excluded.filename,
  mime_type = excluded.mime_type,
  storage_ref = excluded.storage_ref,
  built_at = excluded.built_at,
  state = excluded.state,
  metadata_ref = excluded.metadata_ref,
  normalized_ref = excluded.normalized_ref,
  raw_ref = excluded.raw_ref
`

type UpsertArtifactParams struct {
	ID            string
	ReleaseID     string
	TrackID       string
	ArtifactKind  string
	IsCanonical   int64
	Filename      string
	MimeType      string
	Sha256        string
	StorageRef    string
	BuiltAt       string
	State         string
	MetadataRef   string
	NormalizedRef string
	RawRef        string
}

func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) error {
	_, err := q.db.ExecContext(ctx, upsertArtifact,
		arg.ID,
		arg.ReleaseID,
		arg.TrackID,
		arg.ArtifactKind,
		arg.IsCanonical,
		arg.Filename,
		arg.MimeType,
		arg.Sha256,
		arg.StorageRef,
		arg.BuiltAt,
		arg.State,
		arg.MetadataRef,
		arg.NormalizedRef,
		arg.RawRef,
	)
	return err
}

const upsertPublishRecord = `-- name: UpsertPublishRecord :exec
INSERT INTO publish_records (id, artifact_id, target_id, target_kind, target_ref, publish_hash, published_at, status, message)
VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9
)
ON CONFLICT(artifact_id, target_id, publish_hash) DO UPDATE SET
  target_kind = excluded.target_kind,
  target_ref = excluded.target_ref,
  published_at = excluded.published_at,
  status = excluded.status,
  message = excluded.message
`

type UpsertPublishRecordParams struct {
	ID          string
	ArtifactID  string
	TargetID    string
	TargetKind  string
	TargetRef   string
	PublishHash string
	PublishedAt string
	Status      string
	Message     string
}

func (q *Queries) UpsertPublishRecord(ctx context.Context, arg UpsertPublishRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertPublishRecord,
		arg.ID,
		arg.ArtifactID,
		arg.TargetID,
		arg.TargetKind,
		arg.TargetRef,
		arg.PublishHash,
		arg.PublishedAt,
		arg.Status,
		arg.Message,
	)
	return err
}

const upsertRelease = `-- name: UpsertRelease :exec
INSERT INTO releases (
  id, source_id, provider_release_id, url, title, published_at, edited_at,
  post_type, visibility_state, normalized_payload_ref, raw_payload_ref,
  content_hash, discovered_at, status
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9, ?10, ?11,
  ?12, ?13, ?14
)
ON CONFLICT(source_id, provider_release_id) DO UPDATE SET
  url = excluded.url,
  title = excluded.title,
  published_at = excluded.published_at,
  edited_at = excluded.edited_at,
  post_type = excluded.post_type,
  visibility_state = excluded.visibility_state,
  normalized_payload_ref = excluded.normalized_payload_ref,
  raw_payload_ref = excluded.raw_payload_ref,
  content_hash = excluded.content_hash,
  discovered_at = excluded.discovered_at,
  status = excluded.status
`

type UpsertReleaseParams struct {
	ID                   string
	SourceID             string
	ProviderReleaseID    string
	Url                  string
	Title                string
	PublishedAt          string
	EditedAt             string
	PostType             string
	VisibilityState      string
	NormalizedPayloadRef string
	RawPayloadRef        string
	ContentHash          string
	DiscoveredAt         string
	Status               string
}

func (q *Queries) UpsertRelease(ctx context.Context, arg UpsertReleaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertRelease,
		arg.ID,
		arg.SourceID,
		arg.ProviderReleaseID,
		arg.Url,
		arg.Title,
		arg.PublishedAt,
		arg.EditedAt,
		arg.PostType,
		arg.VisibilityState,
		arg.NormalizedPayloadRef,
		arg.RawPayloadRef,
		arg.ContentHash,
		arg.DiscoveredAt,
		arg.Status,
	)
	return err
}

const upsertReleaseAssignment = `-- name: UpsertReleaseAssignment :exec
INSERT INTO release_assignments (release_id, track_id, rule_id, release_role, confidence)
VALUES (
  ?1, ?2, ?3, ?4, ?5
)
ON CONFLICT(release_id) DO UPDATE SET
  track_id = excluded.track_id,
  rule_id = excluded.rule_id,
  release_role = excluded.release_role,
  confidence = excluded.confidence
`

type UpsertReleaseAssignmentParams struct {
	ReleaseID   string
	TrackID     string
	RuleID      string
	ReleaseRole string
	Confidence  float64
}

func (q *Queries) UpsertReleaseAssignment(ctx context.Context, arg UpsertReleaseAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertReleaseAssignment,
		arg.ReleaseID,
		arg.TrackID,
		arg.RuleID,
		arg.ReleaseRole,
		arg.Confidence,
	)
	return err
}

const upsertSource = `-- name: UpsertSource :exec
INSERT INTO sources (
  id, provider, source_url, source_type, creator_id, creator_name,
  auth_profile_id, enabled, sync_cursor, last_synced_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10
)
ON CONFLICT(id) DO UPDATE SET
  provider = excluded.provider,
  source_url = excluded.source_url,
  source_type = excluded.source_type,
  creator_id = excluded.creator_id,
  creator_name = excluded.creator_name,
  auth_profile_id = excluded.auth_profile_id,
  enabled = excluded.enabled,
  sync_cursor = excluded.sync_cursor,
  last_synced_at = excluded.last_synced_at
`

type UpsertSourceParams struct {
	ID            string
	Provider      string
	SourceUrl     string
	SourceType    string
	CreatorID     string
	CreatorName   string
	AuthProfileID string
	Enabled       int64
	SyncCursor    string
	LastSyncedAt  string
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertSource,
		arg.ID,
		arg.Provider,
		arg.SourceUrl,
		arg.SourceType,
		arg.CreatorID,
		arg.CreatorName,
		arg.AuthProfileID,
		arg.Enabled,
		arg.SyncCursor,
		arg.LastSyncedAt,
	)
	return err
}

const upsertTrack = `-- name: UpsertTrack :exec
INSERT INTO story_tracks (
  id, source_id, track_key, track_name, canonical_author, series_meta,
  output_policy, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9
)
ON CONFLICT(source_id, track_key) DO UPDATE SET
  track_name = excluded.track_name,
  canonical_author = excluded.canonical_author,
  series_meta = excluded.series_meta,
  output_policy = excluded.output_policy,
  updated_at = excluded.updated_at
`

type UpsertTrackParams struct {
	ID              string
	SourceID        string
	TrackKey        string
	TrackName       string
	CanonicalAuthor string
	SeriesMeta      string
	OutputPolicy    string
	CreatedAt       string
	UpdatedAt       string
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.ID,
		arg.SourceID,
		arg.TrackKey,
		arg.TrackName,
		arg.CanonicalAuthor,
		arg.SeriesMeta,
		arg.OutputPolicy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
